// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUwJspe9_8fuhEDyeLR-OIUGC9YlvQ2bo',
    appId: '1:534993812661:web:855e976203fe12c7ec52fc',
    messagingSenderId: '534993812661',
    projectId: 'cybersocialnew2026',
    authDomain: 'cybersocialnew2026.firebaseapp.com',
    storageBucket: 'cybersocialnew2026.firebasestorage.app',
    measurementId: 'G-REZZ24G9BM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmpbOqrfc2Bd79wZkcQtqXL_-P55h0HCk',
    appId: '1:534993812661:android:8e9cbcaf1d6825fbec52fc',
    messagingSenderId: '534993812661',
    projectId: 'cybersocialnew2026',
    storageBucket: 'cybersocialnew2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBirWID3EDqjqiwc25GyqxsBT0MUbhR_x0',
    appId: '1:534993812661:ios:266f139819788e68ec52fc',
    messagingSenderId: '534993812661',
    projectId: 'cybersocialnew2026',
    storageBucket: 'cybersocialnew2026.firebasestorage.app',
    iosClientId: '534993812661-6oe6sag5l5cb1nhvesbpvdapf74nmqh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialSecureApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBirWID3EDqjqiwc25GyqxsBT0MUbhR_x0',
    appId: '1:534993812661:ios:266f139819788e68ec52fc',
    messagingSenderId: '534993812661',
    projectId: 'cybersocialnew2026',
    storageBucket: 'cybersocialnew2026.firebasestorage.app',
    iosClientId: '534993812661-6oe6sag5l5cb1nhvesbpvdapf74nmqh0.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialSecureApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUwJspe9_8fuhEDyeLR-OIUGC9YlvQ2bo',
    appId: '1:534993812661:web:5105860ba7aea989ec52fc',
    messagingSenderId: '534993812661',
    projectId: 'cybersocialnew2026',
    authDomain: 'cybersocialnew2026.firebaseapp.com',
    storageBucket: 'cybersocialnew2026.firebasestorage.app',
    measurementId: 'G-LYWRXLZHWJ',
  );
}
